# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiserver', '0002_userroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroom',
            name='userID',
            field=models.CharField(max_length=200),
        ),
    ]
