# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiserver', '0006_userinfo_usernickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='userNickName',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
