# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiserver', '0008_auto_20180304_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiPlayRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='default', max_length=200)),
                ('mulRoomName', models.CharField(default='default', max_length=200)),
                ('maxNumPeople', models.IntegerField(default='8')),
            ],
        ),
    ]
