# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiserver', '0010_multiplayroom_roomjson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplayroom',
            name='maxNumPeople',
        ),
        migrations.AddField(
            model_name='multiplayroom',
            name='NumPeople',
            field=models.IntegerField(default='1'),
        ),
    ]
