# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-08 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oiserver', '0011_auto_20180320_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNickName', models.CharField(default='default', max_length=200)),
                ('videoData', models.FileField(upload_to='video/')),
            ],
        ),
    ]
