# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oiserver', '0012_uservideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('content', models.TextField(max_length=2000)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postNum', models.AutoField(primary_key=True, serialize=False)),
                ('postDate', models.DateTimeField(auto_now_add=True)),
                ('postTitle', models.CharField(default='default', max_length=200)),
                ('postContent', models.CharField(default='default', max_length=1000)),
                ('imageData', models.ImageField(upload_to='image/post/')),
                ('postAthor', models.CharField(default='default', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oiserver.Post'),
        ),
    ]
